### ISSUE TITLE
Location Page Events Widget Not Wrapping on Mobile

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#297] opened 2018-04-10 12:01 UTC
![image](https://user-images.githubusercontent.com/1933400/38555720-2eb8a3c8-3c95-11e8-8f62-c427406afd73.png)

**Comment by mxsnyder** [comment] 2018-04-10 20:18
`flex-direction: column` at `$screen-md` and below.

**Comment by martypowell** [comment] 2018-04-11 11:48
@mxsnyder i think the markup, maybe just need the `flex flex-column` classes add. See the homepage for an example.

**Comment by danfox01** [comment] 2018-04-11 12:19
Let me know if this is confirmed. I can assign it out for someone to update the markup.

**Comment by mxsnyder** [comment] 2018-04-11 12:48
It's not the markup, there's a media query doing this in `homepage.min.css`:

```CSS
@media (max-width: 991px)
.events-wrapper .container .row.flex {
    display: block;
}
```

**Comment by martypowell** [comment] 2018-04-11 12:50
We should rework this then, so that the grid can handle this. There is no need for this to be specific to this component.

**Comment by mxsnyder** [comment] 2018-04-11 14:35
It won't be specific to the component -- I'm adding a new `.flex-column-md` class that will take care of what we need.

**Comment by martypowell** [comment] 2018-04-11 18:28
@mxsnyder sounds great then.

**Comment by mxsnyder** [comment] 2018-04-11 20:08
@danfox01 Done in dev.

https://dev.bcpl.info/locations/arbutus/index.html

**Comment by danfox01** [comment] 2018-04-11 20:09
Perfect

**Comment by mxsnyder** [comment] 2018-04-11 20:14
PR submitted.

**Comment by mxsnyder** [comment] 2018-04-12 12:41
Looks like the PR closed this one. Reopening.

**Comment by mxsnyder** [comment] 2018-04-13 13:30
@danfox01 Please verify and close out.

**Closed** 2018-04-27 11:04 UTC
Labels: bug
