### ISSUE TITLE
Troubleshoot email switcher on Teacher Collection form

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#304] opened 2018-04-10 17:20 UTC
Even though the email switcher was designed for the My Librarian form, we thought it would probably work for other forms as well. I hooked it up to Teacher Collection, but it ain't working. Not sure if it was my error or the script.

It's the second button on this page: https://www.bcpl.info/youth/teachers.html

Form is located at **Modules > Advanced Forms > BCPL > bcpl_teacherscollection**

**Comment by mxsnyder** [comment] 2018-04-10 17:26
All you need to do is change the ID on the branch dropdown to "whichBranch" and it'll work.

**Comment by danfox01** [comment] 2018-04-10 17:31
I'm seeing this in the markup:

`<select id="whichBranch" name="whichBranch" class="seSelect seRequiredElement" size="1">`

What am I missing?

**Comment by danfox01** [comment] 2018-04-11 21:07
@mxsnyder See my comment above -- that ID is already in place on the teacher collection form.

**Comment by mxsnyder** [comment] 2018-04-12 17:07
@danfox01 It looks like this is actually the **bcpl_assignmentalert** form.

**Comment by mxsnyder** [comment] 2018-04-12 17:32
@danfox01 The issue is the two forms on one page. It's not insurmountable, it's just what's happening. I'm working on a fix now.

Kudos to @martypowell for helping me figure this out.

**Comment by mxsnyder** [comment] 2018-04-12 17:41
I have a fix for this in dev. Submitting PR momentarily.

**Comment by danfox01** [comment] 2018-04-19 12:56
Going to hold off closing this until we do more testing today, since we ran into a small issue last night during the change.

**Closed** 2018-04-27 11:03 UTC
Labels: bug, support
