### ISSUE TITLE
Polaris - New Sound Recordings is Missing Content Area Styling

### ISSUE THREAD

**Issue by sdurphy** [baltimorecounty/BCPL-assets#322] opened 2018-04-13 20:14 UTC
In Polaris the New Sound Recordings page in the New Titles section is missing the styling for the content area.

Example: https://catalog.bcpl.lib.md.us/polaris/Search/newreleases.aspx?ListingTypeID=28&ctx=1.1033.0.0.6

**Comment by martypowell** [comment] 2018-04-16 14:53
duplicate of #320

**Closed by martypowell** 2018-04-16 14:53 UTC
Labels: polaris
