### ISSUE TITLE
Add indication that when user is logged in.

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#511] opened 2018-06-12 17:37 UTC
fyi @danfox01 

Maybe just add a user fa icon the user name next to the “print” icon? Clicking the name take you to the main account screen? Just a thought. Open to ideas and we can tweak later.

**Comment by jdomasky** [comment] 2018-06-13 17:18
This will be a helpful enhancement. I suggest displaying an icon similar to Google, when a user doesn't have a profile photo, such as this:
![image](https://user-images.githubusercontent.com/13354985/41367015-d8733164-6f0b-11e8-8582-afa6c15b3ffe.png)
In BCPL colors, of course.
I don't think we should display the user name because the user name for most customers is their library card number. So, this would be displayed: 21183012345678.

**Comment by sdurphy** [comment] 2018-06-13 17:37
For example:
![screen-shot-2018-06-13-at-1 25 54-pm](https://user-images.githubusercontent.com/2189638/41368097-e77205ac-6f0e-11e8-8ed6-16ec68a8d53e.jpg)

**Comment by danfox01** [comment] 2018-06-13 18:48
When you are logged in to Polaris currently, doesn't it display "Last Name, First Name" in the account details menu (on the left). Can we use that same bit of data in the location on the right as well?

We should also discuss what, if anything is displayed here when the user is not logged in, and how this element will impact the user's expectation of the main Account menu as well.

**Comment by jsmith176** [comment] 2018-06-15 17:28
@danfox01 This is implemented in ils-test. I have the icon displayed as "Log in" initially and then the users first name after logging in. What do you think?

**Comment by jdomasky** [comment] 2018-06-15 18:41
This looks great! I just tried it in ils-test. It says "HI JASON". When I select it, I'm taken to My Account, which is expected.
However, I noticed when I'm browsing any of the My Account pages, the URL is different (it links to an error message):
https://ils-test.bcpl.lib.md.us/polaris/patronaccount/polaris/patronaccount/

**Comment by sdurphy** [comment] 2018-06-15 18:58
This does look great! 

Is it possible to have it display at mobile size even though we hide the print and share at mobile size?

(I've attached a comp.)
![screen shot 2018-06-15 at 2 59 31 pm](https://user-images.githubusercontent.com/2189638/41484944-9be85d26-70ac-11e8-8f04-36cfa6d24fa6.png)

**Comment by jsmith176** [comment] 2018-06-15 19:23
@jdomasky I see what happened there. I can fix that!
@sdurphy I'm sure that can be done. Let me tinker with it.

**Comment by danfox01** [comment] 2018-06-18 15:01
This looks awesome! Nice work @jsmith176!

I just have a few UX questions we need to think through before this goes live, so I'd like to hold it back from the June 24 upgrade. Can we plan to release this separately, after the upgrade is complete?

**Comment by jsmith176** [comment] 2018-06-20 12:53
@danfox01 I don't see an issue with doing a separate release. What do you think @martypowell ?

**Comment by martypowell** [comment] 2018-06-25 12:09
@jsmith176 go ahead and move this back into ils-test and assign to dan for testing.

**Comment by danfox01** [comment] 2018-07-03 15:45
In terms of testing, this look good. I want to discuss the UX of adding this with a @hburnopp and @sdurphy . Moving this to blocked until we have a chance to chat about it.

**Comment by danfox01** [comment] 2018-10-30 15:17
FYI, this was accidentally released along with the Polaris alert fix last week. Confirmed with BCPL that we can let this stand, though it may need a few tweaks in the future.

**Closed by danfox01** 2018-10-30 15:17 UTC
Labels: polaris
