### ISSUE TITLE
Polaris - New Videos is Missing Content Area Styling

### ISSUE THREAD

**Issue by sdurphy** [baltimorecounty/BCPL-assets#321] opened 2018-04-13 20:13 UTC
In Polaris the New Videos page in the New Titles section is missing the styling for the content area.

Example: https://catalog.bcpl.lib.md.us/polaris/Search/newreleases.aspx?ListingTypeID=27&ctx=1.1033.0.0.6

**Comment by martypowell** [comment] 2018-04-16 14:52
duplicate of #320

**Closed by martypowell** 2018-04-16 14:52 UTC
Labels: polaris
